/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uraroji_garage_android_lame_Lame_Builder */

#ifndef _Included_com_uraroji_garage_android_lame_Lame_Builder
#define _Included_com_uraroji_garage_android_lame_Lame_Builder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
