/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uraroji_garage_android_lame_Lame */

#ifndef _Included_com_uraroji_garage_android_lame_Lame
#define _Included_com_uraroji_garage_android_lame_Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uraroji_garage_android_lame_Lame
 * Method:    log
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_uraroji_garage_android_lame_Lame_log
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
