/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uraroji_garage_android_lame_Encoder */

#ifndef _Included_com_uraroji_garage_android_lame_Encoder
#define _Included_com_uraroji_garage_android_lame_Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uraroji_garage_android_lame_Encoder
 * Method:    init
 * Signature: (IIIIILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_uraroji_garage_android_lame_Encoder_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_uraroji_garage_android_lame_Encoder
 * Method:    encode
 * Signature: (I[S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_uraroji_garage_android_lame_Encoder_encode
  (JNIEnv *, jclass, jint, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_uraroji_garage_android_lame_Encoder
 * Method:    encodeBufferInterleaved
 * Signature: (I[SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_uraroji_garage_android_lame_Encoder_encodeBufferInterleaved
  (JNIEnv *, jclass, jint, jshortArray, jint, jbyteArray);

/*
 * Class:     com_uraroji_garage_android_lame_Encoder
 * Method:    flush
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_uraroji_garage_android_lame_Encoder_flush
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_uraroji_garage_android_lame_Encoder
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_uraroji_garage_android_lame_Encoder_close
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
